openapi: 3.0.0
info:
  title: 'Buspark Admin Api-v2 '
  description: 'Buspark Admin Api-v2 '
  version: '1.0'
  x-logo:
    url: https://github.com/joolfe/logoBanner.png
    backgroundColor: '#FFFFFF'
    altText: logo
  termsOfService: '#'
  contact:
    name: Scodus
    url: https://scodus.com
    email: scodusnp@gmail.com
  license:
    name: MIT
    url: https://es.wikipedia.org/wiki/Licencia_MIT
servers:
  - url: https://buspark.scodus.com
    description: Base URL
  - url: https://ticketing.madani.com.np
    description: Base URL
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
    noauthAuth:
      type: http
      scheme: noauth
tags:
  - name: Authentication
  - name: association
  - name: bus
  - name: bus-schedule
  - name: bus-schedule > for booking
  - name: bus booking
  - name: chalani
  - name: company
  - name: contact-us
  - name: departure list
  - name: location
  - name: role
  - name: route
  - name: sales report
  - name: site-setting
paths:
  /api/v2/login:
    post:
      tags:
        - Authentication
      summary: login
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                email:
                  type: string
                  example: aayushpandey616@gmail.com
                password:
                  type: string
                  example: P@ssw0rd
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/v2/logout:
    post:
      tags:
        - Authentication
      summary: logout
      requestBody:
        content: {}
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/v2/user-detail:
    get:
      tags:
        - Authentication
      summary: get profile
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    post:
      tags:
        - Authentication
      summary: update profile
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                first_name:
                  type: string
                  example: samiti
                last_name:
                  type: integer
                  example: '1'
                image:
                  type: string
                  format: binary
                _method:
                  type: string
                  example: PUT
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/v2/password-change:
    post:
      tags:
        - Authentication
      summary: change password
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                old_password:
                  type: integer
                  example: '1234'
                new_password:
                  type: integer
                  example: '12345'
                new_password_confirmation:
                  type: integer
                  example: '12345'
                _method:
                  type: string
                  example: PUT
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/v2/refresh-token/{refresh_token}:
    post:
      tags:
        - Authentication
      summary: refresh token
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
      security:
        - noauthAuth: []
      parameters:
        - name: refresh_token
          in: path
          schema:
            type: string
          required: true
          example: '{{refresh_token}}'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/v2/reset-password-mail:
    post:
      tags:
        - Authentication
      summary: reset password mail
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                email:
                  type: string
                  example: bikashxaus@gmail.com
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/v2/reset-password-otp-verification:
    post:
      tags:
        - Authentication
      summary: reset password otp verification
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                otp:
                  type: string
                  example: kGbD
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/v2/reset-password:
    post:
      tags:
        - Authentication
      summary: reset password
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                password:
                  type: string
                  example: P@ssw0rd
                password_confirmation:
                  type: string
                  example: P@ssw0rd
                token:
                  type: string
                  example: kGbD
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/v2/association:
    get:
      tags:
        - association
      summary: list
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/v2/association/{slug}:
    get:
      tags:
        - association
      summary: single
      security:
        - bearerAuth: []
      parameters:
        - name: slug
          in: path
          schema:
            type: string
          required: true
          example: madonna-savage
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/v2/bus:
    get:
      tags:
        - bus
      summary: list
      security:
        - bearerAuth: []
      parameters:
        - name: route_id
          in: query
          schema:
            type: integer
          example: '27'
        - name: company_id
          in: query
          schema:
            type: integer
          example: '1'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/v2/bus/list/paginated:
    get:
      tags:
        - bus
      summary: list data
      security:
        - bearerAuth: []
      parameters:
        - name: paginate
          in: query
          schema:
            type: integer
          example: '1'
        - name: page
          in: query
          schema:
            type: string
        - name: limit
          in: query
          schema:
            type: string
        - name: search_keyword
          in: query
          schema:
            type: string
        - name: route_id
          in: query
          schema:
            type: integer
          example: '27'
        - name: company_id
          in: query
          schema:
            type: integer
          example: '1'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/v2/bus/{id}:
    get:
      tags:
        - bus
      summary: single
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          schema:
            type: integer
          required: true
          example: '38'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/v2/bus/{id}/seats:
    get:
      tags:
        - bus
      summary: bus seats
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          schema:
            type: integer
          required: true
          example: '38'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/v2/bus-schedule/search/for-booking:
    get:
      tags:
        - bus-schedule > for booking
      summary: search list
      security:
        - bearerAuth: []
      parameters:
        - name: from
          in: query
          schema:
            type: integer
          example: '1'
        - name: to
          in: query
          schema:
            type: integer
          example: '9'
        - name: date
          in: query
          schema:
            type: string
          example: '2080-05-31'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/v2/bus-schedule/{bus_schedule_id}/for-booking:
    get:
      tags:
        - bus-schedule > for booking
      summary: single (get bus seat)
      security:
        - bearerAuth: []
      parameters:
        - name: bus_schedule_id
          in: path
          schema:
            type: integer
          required: true
          example: '127'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/v2/bus-schedule:
    get:
      tags:
        - bus-schedule
      summary: list
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    post:
      tags:
        - bus-schedule
      summary: store
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                route_id:
                  type: integer
                  example: '1'
                bus_id:
                  type: integer
                  example: '38'
                departure_date:
                  type: string
                  example: '2080-11-01'
                departure_date_ad:
                  type: string
                  example: '2023-11-07'
                departure_time:
                  type: string
                  example: '20:00'
                status:
                  type: string
                  example: Active
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/v2/bus-schedule/{id}:
    get:
      tags:
        - bus-schedule
      summary: single
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          schema:
            type: integer
          required: true
          example: '153'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    post:
      tags:
        - bus-schedule
      summary: update
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                _method: PUT
                departure_time: '21:00'
                status: Active
                is_discount_available: 1
                main_route_discount: 3
                sub_route_discount:
                  - from_id: 1
                    to_id: 9
                    price: 12
                    discount: 2
                    status: Active
                  - from_id: 8
                    to_id: 9
                    price: 10
                    discount: null
                    status: Active
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          schema:
            type: integer
          required: true
          example: '127'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/v2/bus-schedule/route/{route_id}/buses:
    get:
      tags:
        - bus-schedule
      summary: get route buses
      security:
        - bearerAuth: []
      parameters:
        - name: route_id
          in: path
          schema:
            type: integer
          required: true
          example: '1'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/v2/bus-schedule/bus/{bus_id}/route:
    get:
      tags:
        - bus-schedule
      summary: get bus route
      security:
        - bearerAuth: []
      parameters:
        - name: bus_id
          in: path
          schema:
            type: integer
          required: true
          example: '38'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/v2/bus-schedule-search-by-dates:
    get:
      tags:
        - bus-schedule
      summary: list search by dates
      security:
        - bearerAuth: []
      parameters:
        - name: paginate
          in: query
          schema:
            type: integer
          example: '1'
        - name: perPage
          in: query
          schema:
            type: integer
          example: '1'
        - name: currentPage
          in: query
          schema:
            type: integer
          example: '2'
        - name: from_date
          in: query
          schema:
            type: string
          example: '2080-04-29'
        - name: to_date
          in: query
          schema:
            type: string
          example: '2080-06-29'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/v2/bus-schedule-search:
    get:
      tags:
        - bus-schedule
      summary: list by departure date and route
      security:
        - bearerAuth: []
      parameters:
        - name: departure_date
          in: query
          schema:
            type: string
          example: '2080-08-30'
        - name: route_id
          in: query
          schema:
            type: integer
          example: '1'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/v2/bus-schedule/{id}/status-change:
    post:
      tags:
        - bus-schedule
      summary: status change
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                _method:
                  type: string
                  example: PUT
                status:
                  type: string
                  example: Active
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          schema:
            type: integer
          required: true
          example: '120'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/v2/bus-schedule/{id}/booking-status-change:
    post:
      tags:
        - bus-schedule
      summary: booking status change
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                _method:
                  type: string
                  example: PUT
                booking_status:
                  type: string
                  example: Open
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          schema:
            type: integer
          required: true
          example: '120'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/v2/bus-schedule/{id}/departure-time-change:
    post:
      tags:
        - bus-schedule
      summary: departure time change
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                _method:
                  type: string
                  example: PUT
                departure_time:
                  type: string
                  example: '21:00'
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          schema:
            type: integer
          required: true
          example: '120'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/v2/bus-schedule/{id}/bus-seats:
    get:
      tags:
        - bus-schedule
      summary: scheduled bus seats
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          schema:
            type: integer
          required: true
          description: '170'
          example: '87'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/v2/bus-schedule/{id}/bus-seats/enable-disable:
    post:
      tags:
        - bus-schedule
      summary: scheduled bus seats enable disable
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                seat_id:
                  - 53
                  - 41
                  - 54
                  - 50
                  - 46
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          schema:
            type: integer
          required: true
          example: '120'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/v2/bus-schedule/{id}/bus-seats/available-to:
    post:
      tags:
        - bus-schedule
      summary: scheduled bus seats enabled Availability
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                seat_id:
                  - 53
                  - 41
                  - 54
                available_to: Online
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          schema:
            type: integer
          required: true
          example: '120'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/v2/bus-schedule/{id}/counters:
    get:
      tags:
        - bus-schedule
      summary: scheduled bus seats Get Counters
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          schema:
            type: integer
          required: true
          example: '170'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/v2/bus-schedule/{id}/bus-seats/counter-assign:
    post:
      tags:
        - bus-schedule
      summary: scheduled bus seats Counter Assign
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                seat_id:
                  - 49
                  - 53
                counter_availability: 21
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          schema:
            type: integer
          required: true
          example: '170'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/v2/bus-schedule/{id}/route-bus-facility-type-price:
    get:
      tags:
        - bus-schedule
      summary: bus schedule->route bus facility type price
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          schema:
            type: integer
          required: true
          example: '127'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/v2/bus-schedule/sub-route-discount/{id}:
    post:
      tags:
        - bus-schedule
      summary: store sub route discount
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                _method: PUT
                is_discount_available: 1
                main_route_discount: 3
                sub_route_discount:
                  - from_id: 1
                    to_id: 9
                    price: 12
                    discount: 2
                    status: Active
                  - from_id: 8
                    to_id: 9
                    price: 10
                    discount: 4
                    status: Active
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          schema:
            type: integer
          required: true
          example: '127'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/v2/bus-booking/pre-booking:
    get:
      tags:
        - bus booking
      summary: pre booking
      security:
        - bearerAuth: []
      parameters:
        - name: from
          in: query
          schema:
            type: integer
          example: '1'
        - name: to
          in: query
          schema:
            type: integer
          example: '2'
        - name: schedule_id
          in: query
          schema:
            type: integer
          example: '170'
        - name: date
          in: query
          schema:
            type: string
          example: '2080-10-29'
        - name: seat_id[]
          in: query
          schema:
            type: integer
          description: seat_id is array where seat_id = [53,54]
          example: '41'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/v2/bus-booking/pre-booking-timeout:
    post:
      tags:
        - bus booking
      summary: pre booking timeout
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                schedule_id: 170
                seat_id:
                  - 41
                  - 42
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/v2/bus-booking/store:
    post:
      tags:
        - bus booking
      summary: store booking
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                schedule_id: 170
                route_id: 1
                pickup_location: X-place
                drop_location: X-place
                discount: 1
                paid: 15
                contact_phone: 98xxxxxxxx
                contact_name: X-man Mu
                seat_id:
                  - 43
                  - 54
                sub_route_price:
                  from_id: 1
                  to_id: 9
                  sub_route_from: KTM
                  sub_route_to: Kohalpur
                  price: 12
                  discount: 2
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/v2/bus-booking/{id}/update-detail:
    post:
      tags:
        - bus booking
      summary: update booking details
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                _method: PUT
                drop_location: 1X-place00
                pickup_location: 2A-place00
                contact_phone: 98xxxxx000
                contact_name: X-man 00000
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          schema:
            type: integer
          required: true
          example: '725'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/v2/bus-booking/{id}/update-booked-seat:
    post:
      tags:
        - bus booking
      summary: update booking seats
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                _method: PUT
                new_booked_seat_id:
                  - 55
                old_booked_seat_id: []
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          schema:
            type: integer
          required: true
          example: '720'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/v2/bus-booking/{id}/cancel:
    post:
      tags:
        - bus booking
      summary: cancel whole booking
      requestBody:
        content: {}
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          schema:
            type: integer
          required: true
          example: '670'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/v2/bus-booking/{id}/seat-cancel:
    post:
      tags:
        - bus booking
      summary: seat wise cancel
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                new_booked_seat_id:
                  - 48
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          schema:
            type: integer
          required: true
          example: '723'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/v2/bus-booking/users-my-booking/users-from-role:
    get:
      tags:
        - bus booking
      summary: Users/my booking users from role
      security:
        - bearerAuth: []
      parameters:
        - name: role_id
          in: query
          schema:
            type: integer
          example: '3'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/v2/bus-booking/users-my-booking/users:
    get:
      tags:
        - bus booking
      summary: Users/my booking - users
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/v2/bus-booking/users-my-booking:
    get:
      tags:
        - bus booking
      summary: Users/my booking history
      security:
        - bearerAuth: []
      parameters:
        - name: from_date
          in: query
          schema:
            type: string
          description: Departure Date From
          example: '2080-01-31'
        - name: to_date
          in: query
          schema:
            type: string
          description: Departure Date To
          example: '2080-08-31'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/v2/bus-booking-search:
    get:
      tags:
        - bus booking
      summary: list by bus-schedule
      security:
        - bearerAuth: []
      parameters:
        - name: bus_schedule_id
          in: query
          schema:
            type: integer
          example: '153'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/v2/bus-booking-cancelled-search:
    get:
      tags:
        - bus booking
      summary: list Cancelled by bus-schedule
      security:
        - bearerAuth: []
      parameters:
        - name: bus_schedule_id
          in: query
          schema:
            type: integer
          example: '117'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/v2/bus-booking/{id}:
    get:
      tags:
        - bus booking
      summary: single
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          schema:
            type: integer
          required: true
          example: '687'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/v2/chalani-list-search:
    get:
      tags:
        - chalani
      summary: list
      security:
        - bearerAuth: []
      parameters:
        - name: departure_date
          in: query
          schema:
            type: string
          example: '2080-04-32'
        - name: bus_id
          in: query
          schema:
            type: integer
          example: '29'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/v2/company:
    get:
      tags:
        - company
      summary: list
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/v2/company/{slug}:
    get:
      tags:
        - company
      summary: single
      security:
        - bearerAuth: []
      parameters:
        - name: slug
          in: path
          schema:
            type: string
          required: true
          example: hamilton-and-rowland-co
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/v2/contact-us:
    post:
      tags:
        - contact-us
      summary: contact us
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                name:
                  type: string
                  example: A B
                subject:
                  type: string
                  example: abc
                message:
                  type: string
                  example: adsfghjk
                email:
                  type: string
                  example: xyz@gmail.com
                phone_no:
                  type: integer
                  example: '9876543210'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/v2/departure-list-search:
    get:
      tags:
        - departure list
      summary: list
      security:
        - bearerAuth: []
      parameters:
        - name: departure_date
          in: query
          schema:
            type: string
          example: '2080-04-32'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/v2/location:
    get:
      tags:
        - location
      summary: list
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/v2/location/{id}:
    get:
      tags:
        - location
      summary: single
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          schema:
            type: integer
          required: true
          example: '12'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/v2/location/by-slug/{slug}:
    get:
      tags:
        - location
      summary: single by slug
      security:
        - bearerAuth: []
      parameters:
        - name: slug
          in: path
          schema:
            type: string
          required: true
          example: finn-wiggins
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/v2/role:
    get:
      tags:
        - role
      summary: list
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/v2/role/{id}:
    get:
      tags:
        - role
      summary: single
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          schema:
            type: integer
          required: true
          example: '3'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/v2/role/{id}/users:
    get:
      tags:
        - role
      summary: role - users
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          schema:
            type: integer
          required: true
          example: '3'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/v2/route:
    get:
      tags:
        - route
      summary: list
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/v2/route/{id}:
    get:
      tags:
        - route
      summary: single
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          schema:
            type: integer
          required: true
          example: '1'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/v2/sales-report-list-counter-online:
    get:
      tags:
        - sales report
      summary: list counter online
      security:
        - bearerAuth: []
      parameters:
        - name: from_date
          in: query
          schema:
            type: string
          example: '2080-04-17'
        - name: to_date
          in: query
          schema:
            type: string
          example: '2080-08-30'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/v2/sales-report-list-all-user:
    get:
      tags:
        - sales report
      summary: list all user
      security:
        - bearerAuth: []
      parameters:
        - name: from_date
          in: query
          schema:
            type: string
          example: '2080-04-17'
        - name: to_date
          in: query
          schema:
            type: string
          example: '2080-08-30'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /api/v2/site-setting:
    get:
      tags:
        - site-setting
      summary: site-setting
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
